# Generated by Django 5.2.13 on 2026-08-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stage_counts', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'sentinel_agent_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_thread_id', models.CharField(max_length=128)),
                ('gmail_message_id', models.CharField(max_length=128, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('draft_reply', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('drafted', 'Drafted'), ('reviewed', 'Reviewed'), ('sent', 'Sent')], default='detected', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sentinel_recruiter_emails',
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jsearch', 'JSearch'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('adzuna', 'Adzuna')], max_length=20)),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentinel_job_listings',
                'indexes': [models.Index(fields=['source', 'external_id'], name='sentinel_jo_source_36441e_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_listing_per_source')],
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('applied', 'Applied')], max_length=20)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='core.joblisting')),
            ],
            options={
                'db_table': 'sentinel_shortlist',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='draft', max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('extension_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.shortlist')),
            ],
            options={
                'db_table': 'sentinel_applications',
            },
        ),
    ]
