# Generated by Django 5.2.13 on 2026-08-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_encrypted', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_verification', 'Pending Verification'), ('failed', 'Failed')], default='pending_verification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentinel_site_accounts',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_verification', 'Pending Verification'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(choices=[('theirstack', 'TheirStack'), ('jobspipe', 'JobsPipe'), ('adzuna', 'Adzuna')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='site_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.siteaccount'),
        ),
    ]
