# Generated by Django 5.2.13 on 2026-08-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteaccount_application_verification_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_discovery_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'sentinel_schedule_config',
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='graph',
            field=models.CharField(choices=[('discovery', 'Graph 1 — Discovery & Shortlist'), ('application', 'Graph 2 — Per-Application Automation'), ('outcome', 'Graph 3 — Outcome Monitoring')], default='discovery', max_length=20),
        ),
    ]
