# Generated by Django 5.2.13 on 2026-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduleconfig_agentrun_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='signals',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
