# Generated by Django 5.2.13 on 2026-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_joblisting_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='dimension_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
