"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(Path(__file__).resolve().parent / '.env')

# Job-source + Gemini API keys: separate dev keys/accounts exist specifically
# so Graph 1/2 can be exercised for real during development without eating
# into tight production budgets (esp. TheirStack's 200/mo — see
# agent_memory/sentinel_project.md). IS_DEV picks which set loads; sources/
# *.py and graphs/nodes/*.py should read these settings values, not
# os.getenv directly, so there is exactly one place that decides dev vs prod.
IS_DEV = os.getenv('IS_DEV', 'False') == 'True'

if IS_DEV:
    THEIRSTACK_API_KEY = os.getenv('THEIRSTACK_DEV_KEY')
    JOBSPIPE_API_KEY = os.getenv('JOBSPIPE_DEV_KEY')
    ADZUNA_API_KEY = os.getenv('ADZUNA_DEV_KEY')
    ADZUNA_ID = os.getenv('ADZUNA_DEV_ID')
    GEMINI_API_KEY = os.getenv('GEMINI_DEV_KEY')
else:
    THEIRSTACK_API_KEY = os.getenv('THEIRSTACK_API_KEY')
    JOBSPIPE_API_KEY = os.getenv('JOBSPIPE_API_KEY')
    ADZUNA_API_KEY = os.getenv('ADZUNA_API_KEY')
    ADZUNA_ID = os.getenv('ADZUNA_ID')
    GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Gmail API OAuth client (Desktop app type) — used for failure-notification
# emails (core/gmail_notify.py). GMAIL_TOKEN_PATH is where the one-time
# local auth flow caches the refresh token; gitignored, never committed.
# Your own real LinkedIn login — deliberately .env-only, not the DB (see
# agent_memory/sentinel_project.md: SiteAccount is for agent-generated
# per-domain signups, this is your personal static identity).
LINKEDIN_EMAIL = os.getenv('LINKEDIN_EMAIL')
LINKEDIN_PASSWORD = os.getenv('LINKEDIN_PASSWORD')

GOOGLE_CLIENT_ID = os.getenv('CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('CLIENT_KEY')
GMAIL_NOTIFY_ADDRESS = 'manojshendre.1202@gmail.com'
GMAIL_TOKEN_PATH = BASE_DIR / 'gmail_token.json'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
PROD = os.getenv('PROD')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = PROD != "PROD"

if PROD == "PROD":
    ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
